name: courses_workshop
description: This is for web description rendering

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.1
  flutter_bloc: ^6.1.1
  bloc: ^6.1.0
  dio: ^3.0.10
  fluttertoast: ^7.1.6
  shared_preferences: ^0.5.12+4
  outline_material_icons: ^0.1.1
  flutter_rating_bar: ^3.2.0+1
  expansion_tile_card: ^1.1.0
  conditional_builder: ^1.0.2



dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: 'assets/images/logo_learn.png'
  android: true

flutter:

  uses-material-design: true

  assets:
      - assets/images/
  fonts:
    - family: MontserratBold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
    - family: MontserratMeduium
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
    - family: MontserratRegular
      fonts:
        - asset: fonts/Montserrat-Regular.ttf