name: courses_workshop
description: This is for web description rendering

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.3



dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: 'assets/images/logo_learn.png'
  android: true

flutter:

  uses-material-design: true

  assets:
      - assets/images/
